{"name": "test_login_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: User does not exist.\nMessage: unexpected alert open: {Alert text : User does not exist.}\n  (Session info: chrome=109.0.5414.119)\nStacktrace:\n#0 0x5575d140c303 <unknown>\n#1 0x5575d11e0d37 <unknown>\n#2 0x5575d1255db5 <unknown>\n#3 0x5575d123d753 <unknown>\n#4 0x5575d1210a14 <unknown>\n#5 0x5575d1211b7e <unknown>\n#6 0x5575d145b32e <unknown>\n#7 0x5575d145ec0e <unknown>\n#8 0x5575d1441610 <unknown>\n#9 0x5575d145fc23 <unknown>\n#10 0x5575d1433545 <unknown>\n#11 0x5575d14806a8 <unknown>\n#12 0x5575d1480836 <unknown>\n#13 0x5575d149bd13 <unknown>\n#14 0x7f3805218b43 <unknown>", "trace": "venv/lib/python3.9/site-packages/_pytest/fixtures.py:908: in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\nfeatures/steps/test_login.py:32: in step_login_user_successfully\n    login_page.user_is_logged()\npages/actions/login_actions.py:27: in user_is_logged\n    self.is_displayed(Login.userLogged)\npages/actions/base_actions.py:36: in is_displayed\n    WebDriverWait(self.browser, timeout=10).until(\nvenv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:86: in until\n    value = method(self._driver)\nvenv/lib/python3.9/site-packages/selenium/webdriver/support/expected_conditions.py:139: in _predicate\n    return _element_if_visible(driver.find_element(*locator))\nvenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:830: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\nvenv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:440: in execute\n    self.error_handler.check_response(response)\nvenv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:244: in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\nE   selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: User does not exist.\nE   Message: unexpected alert open: {Alert text : User does not exist.}\nE     (Session info: chrome=109.0.5414.119)\nE   Stacktrace:\nE   #0 0x5575d140c303 <unknown>\nE   #1 0x5575d11e0d37 <unknown>\nE   #2 0x5575d1255db5 <unknown>\nE   #3 0x5575d123d753 <unknown>\nE   #4 0x5575d1210a14 <unknown>\nE   #5 0x5575d1211b7e <unknown>\nE   #6 0x5575d145b32e <unknown>\nE   #7 0x5575d145ec0e <unknown>\nE   #8 0x5575d1441610 <unknown>\nE   #9 0x5575d145fc23 <unknown>\nE   #10 0x5575d1433545 <unknown>\nE   #11 0x5575d14806a8 <unknown>\nE   #12 0x5575d1480836 <unknown>\nE   #13 0x5575d149bd13 <unknown>\nE   #14 0x7f3805218b43 <unknown>"}, "description": "login.feature: Login User", "start": 1675608874679, "stop": 1675608878309, "uuid": "c1e0fc96-743e-45c2-ada0-77083c186a10", "historyId": "0f34333f28d177ba139585f1e3153982", "testCaseId": "433c93b71e7cd749b8bf2a660bfa517d", "fullName": "features.steps.test_login#test_login_page", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "features.steps"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "manuel-Precision-5560"}, {"name": "thread", "value": "38968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "features.steps.test_login"}]}